### ISSUE TITLE
Crash on 1.20.4

### ISSUE THREAD

**Issue by 7coil** [gXLg/libr-getter#20]
```
[18:09:54] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'void net.minecraft.class_634.method_2883(net.minecraft.class_2596)'
	at com.gxlg.librgetter.Worker.tick(Worker.java:231) ~[libr-getter-1.3.2-Warden.jar:?]
	at net.minecraft.class_636.handler$zmp000$librgetter$tick(class_636.java:1604) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_2927(class_636.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1962) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
```

**Comment by 7coil** [comment]
Additional notes:

- Can reproduce in both singleplayer and multiplayer
- Updating the `build.gradle` for specifically 1.20.4 works - Not sure why
    - I've also changed the Java from 1.8 to 17

**Comment by gXLg** [comment]
Seems that 1.20.4 is not compatible with the Warden release. This will require a new version. I will work on it ASAP.
If you have any suggestions for a cool name for the version based on what is "new" in 1.20.4, let me know!

**Comment by 7coil** [comment]
Can I suggest "Waxed Lightly Weathered Cut Copper Stairs" (or name it after the new Sniffer)

**Comment by gXLg** [comment]
Fixed in [v.1.3.3](https://github.com/gXLg/libr-getter/releases/tag/v1.3.3)
